const sidebars = {
  tutorialSidebar: [
    { type: 'category', label: 'Module 1: Physical AI', items: [{type: 'autogenerated', dirName: '01-physical-ai'}] },
    { type: 'category', label: 'Module 2: ROS 2 System', items: [{type: 'autogenerated', dirName: '02-ros2-system'}] },
    { type: 'category', label: 'Module 3: Digital Twins', items: [{type: 'autogenerated', dirName: '03-digital-twins'}] },
    { type: 'category', label: 'Module 4: NVIDIA Isaac', items: [{type: 'autogenerated', dirName: '04-nvidia-isaac'}] },
    { type: 'category', label: 'Module 5: Humanoid Dev', items: [{type: 'autogenerated', dirName: '05-humanoid-dev'}] },
    { type: 'category', label: 'Module 6: VLA Models', items: [{type: 'autogenerated', dirName: '06-vla-models'}] },
    { type: 'category', label: 'Module 7: Conversational', items: [{type: 'autogenerated', dirName: '07-conversational'}] },
    { type: 'category', label: 'Module 8: Capstone', items: [{type: 'autogenerated', dirName: '08-capstone'}] },
    { type: 'category', label: 'Module 9: Hardware', items: [{type: 'autogenerated', dirName: '09-hardware'}] },
  ],
};
export default sidebars;
